language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g gatsby
script:
  - yarn test
  - yarn build:prod
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
