language: node_js
node_js:
  - "8"
# cache: yarn
addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  CXX=g++-4.8
branches:
  only:
    - master
before_script:
  - "yarn global add https://github.com/firebase/firebase-tools"
  # - "yarn global add gatsby"
script:
  - "yarn lint"
  - "yarn test"
  - "yarn build:prod"
after_success:
  - "firebase deploy --token=${FIREBASE_API_TOKEN}"
